### ISSUE TITLE
CMake structure makes the project hard to consume

### ISSUE THREAD

**Issue by ryanwinter** [azure-rtos/azure-iot-preview#3]
A couple of things,

1. To consume the CMake project directly, I have to recursively clone, which gives me copies of threadx + netxduo + azure embedded SDK. 
2. The azure_iot Cmake project hand craft files from the Embedded SDK project rather than just adding a dependency on it's CMake project.

I think the solution should be to remove the azure-sdk-for-c to the sample folder, its needed to build the final application. And then secondly to make the "azure_iot" cmake project depend on the "az" cmake project which contains the embedded sdk.

**Comment by TiejunMS** [comment]
Ryan, I'm not sure why recursive clone is needed? To build sample project, you only need to clone current repo and initialize submodule.

We will improve the CMake project in the future. Thanks for your feedback!

**Comment by TiejunMS** [comment]
@ryanwinter , updated CMake project to consume Embedded SDK project directly.

**Comment by ryanwinter** [comment]
Point 1 will be resolved when the preview is integrated into netxduo.
