### ISSUE TITLE
Duplicate TLS sessioin in DPS

### ISSUE THREAD

**Issue by ccli8** [azure-rtos/azure-iot-preview#4]
Continuing https://github.com/azure-rtos/getting-started/issues/125, I manually enable `_nx_tcp_socket_establish_notify` in [ST's netxduuo of wifi version](https://github.com/azure-rtos/getting-started/tree/master/STMicroelectronics/STM32L4_L4%2B/lib/netxduo) to verify the DPS of the sample [sample_azure_iot_embedded_sdk](https://github.com/azure-rtos/azure-iot-preview/tree/master/samples/sample_azure_iot_embedded_sdk). DPS failure. Looking into, I meet another issue: tls sessions are duplicate in DPS stage (seen two tls client hello). 

Possible duplicate paths are:

`_nxd_mqtt_client_secure_connect` > `_nxd_mqtt_client_connect` > `nx_secure_tls_session_start`:

https://github.com/azure-rtos/getting-started/blob/829122217a643ce60d0b468c71358fcb9522aa38/STMicroelectronics/STM32L4_L4%2B/lib/netxduo/addons/mqtt/nxd_mqtt_client.c#L3872

`_nxd_mqtt_client_event_process` > `_nxd_mqtt_tcp_establish_process` > `nx_secure_tls_session_start`:

https://github.com/azure-rtos/getting-started/blob/829122217a643ce60d0b468c71358fcb9522aa38/STMicroelectronics/STM32L4_L4%2B/lib/netxduo/addons/mqtt/nxd_mqtt_client.c#L2265

**Comment by TiejunMS** [comment]
Answered in https://github.com/azure-rtos/getting-started/issues/125. Close current issue.

**Comment by ccli8** [comment]
@TiejunMS No. This is another issue. I meet duplicate tls sessions during DPS stage.

**Comment by TiejunMS** [comment]
If the wait option is zero, it returns at https://github.com/azure-rtos/getting-started/blob/829122217a643ce60d0b468c71358fcb9522aa38/STMicroelectronics/STM32L4_L4%2B/lib/netxduo/addons/mqtt/nxd_mqtt_client.c#L3852

TLS session is not expected to be called twice.

**Comment by ccli8** [comment]
Per my finding, `_nxd_mqtt_client_connect` itself doesn't cause duplicate TLS sessions. But another TLS session comes from `nx_clooud` thread:

https://github.com/azure-rtos/azure-iot-preview/blob/d1cb0eb0c22c0d172fdd9a7c927c4e4d494fed1b/nx_cloud/nx_cloud.c#L208

It finally has the sequence:

`_nxd_mqtt_client_event_process` > `_nxd_mqtt_tcp_establish_process` > `nx_secure_tls_session_start`

**Comment by TiejunMS** [comment]
Thanks for your feedback, @ccli8 ! We confirm this issue on STM32L4 board and will fix it before official release.

**Comment by hihigupt** [comment]
Our latest [v6.0_beta3](https://github.com/azure-rtos/azure-iot-preview/releases/tag/v6.0_beta3), has the fix.

**Comment by TiejunMS** [comment]
Define `NX_AZURE_IOT_PROVISIONING_CLIENT_CONNECT_WAIT_OPTION` to `(40 * NX_IP_PERIODIC_RATE)` in your project should solve your issue.

**Comment by ccli8** [comment]
The issue gets fixed after I upgrade to [v6.0_beta3](https://github.com/azure-rtos/azure-iot-preview/releases/tag/v6.0_beta3) and define `NX_AZURE_IOT_PROVISIONING_CLIENT_CONNECT_WAIT_OPTION` to `(40 * NX_IP_PERIODIC_RATE)`. as instructed above. Why the default value of `NX_AZURE_IOT_PROVISIONING_CLIENT_CONNECT_WAIT_OPTION` isn't such? Would you mind explaining briefly the rationale?

**Comment by hihigupt** [comment]
Current driver of stm32L475 does not support non-blocking connect and our previous version of provisioning client only supported non-blocking connect. Now with this current release we added support in provisioning client to support blocking connect. With value of NX_AZURE_IOT_PROVISIONING_CLIENT_CONNECT_WAIT_OPTION, user can define amount of ticks they want to block for connect. Also, we do not want to have default blocking mode that is the reason this value is not (40 * NX_IP_PERIODIC_RATE).

**Comment by ccli8** [comment]
@hihigupt Thanks for your explanation. I will close this issue.
