### ISSUE TITLE
Initial landing page feedback

### ISSUE THREAD

**Issue by jspaith** [azure-rtos/azure-iot-preview#6]
The initial [readme](https://github.com/azure-rtos/azure-iot-preview/blob/master/README.md) works reasonably well and I could build the .elf, but needs some refinement.

* It's not clear what sample I should be using here.  I'm started off with a git clone/cmake, but the IAR and other samples that are ready-to-go maybe more interesting to some class of devs??

  Could document with a guide to who should use which sample and get the pre-built highlighted earlier for folks who may not want to mess with cmake directly?

*  In initial clone instructions
```script
$ git clone https://github.com/azure-rtos/azure-iot-preview.git
$ git submodule update --init
```
  There needs to be a `cd azure-iot-preview` between these.

* Please call out which OS(s) various samples are supported for.  Windows/Linux/Mac??

* Assuming we ever care about Linux builds, do we really need to take a dependency on cmake 3.13?  See [this](https://graspingtech.com/upgrade-cmake/) that Ubuntu 18.04 doesn't support cmake 3.13 or higher from apt and instead requires a length build of cmake from source.

*  In the building the library section a more context would help.  It's not clear what .c file I should be looking at to get the "main()" since there's multiple sample* here for both pnp and non-pnp.  Even just "source code along with more instructions available sample_*" directories would help.

* I'm not an Azure RTOS expert by any stretch, but is code in the ./samples directory such as ./ports and ./lib really samples?  It's not worth a ton of work, but my read at least is the ./samples is ALL code under it recursively which I don't think is case with some of dependent code here.

**Comment by yuxin-azrtos** [comment]
@jspaith and our engineering team are discussing offline. So close it here.
